name: "Release That"
description: "Opinionated GitHub Action to ease the release of a repository"
author: "Romain Lespinasse"
inputs:
  system:
    description: "Release system to use: semantic-release (default), lerna"
    default: "semantic-release"
    required: true
  dry-run:
    description: "Whether to run release in `dry-run` mode"
    default: "false"
    required: true
  without-prefix:
    description: "Remove prefix from released version"
    default: "false"
    required: true
  github-token:
    description: "GitHub Token as provided by secrets"
    default: ${{ github.token }}
    required: true
branding:
  icon: "package"
  color: "gray-dark"
runs:
  using: "composite"
  steps:
    - name: Prepare Current Release System
      run: $GITHUB_ACTION_PATH/current-system.sh
      shell: bash
      env:
        INPUT_SYSTEM: ${{ inputs.system }}
    - name: Launch Current Release System
      uses: ./.current-system
      with:
        dry-run: ${{ inputs.dry-run }}
        without-prefix: ${{ inputs.without-prefix }}
        github-token: ${{ inputs.github-token }}
