name: "Release That"
description: "Opinionated GitHub Action to ease the release of a repository"
author: "Romain Lespinasse"
inputs:
  dry-run:
    description: "Whether to run semantic release in `dry-run` mode"
    default: "false"
    required: true
  major-tag:
    description: "Whether to publish or update a major tag (e.g. v1)"
    default: "auto"
    required: true
  without-prefix:
    description: "Remove prefix from released version"
    default: "false"
    required: true
  github-token:
    description: "GitHub Token as provided by secrets"
    default: ${{ github.token }}
    required: true
outputs:
  # useful outputs from semantic-release-action
  new_release_published:
    description: "Whether a new release was published"
    value: ${{ steps.semantic-release.outputs.new_release_published }}
  new_release_version:
    description: "Version of the new release"
    value: ${{ steps.semantic-release.outputs.new_release_version }}
  new_release_major_version:
    description: "Major version of the new release"
    value: ${{ steps.semantic-release.outputs.new_release_major_version }}
  new_release_minor_version:
    description: "Minor version of the new release"
    value: ${{ steps.semantic-release.outputs.new_release_minor_version }}
  new_release_patch_version:
    description: "Patch version of the new release"
    value: ${{ steps.semantic-release.outputs.new_release_patch_version }}
  last_release_version:
    description: "Version of the previous release, if there was one."
    value: ${{ steps.semantic-release.outputs.last_release_version }}
  major_tag_published:
    description: "Whether a major tag was published"
    value: ${{ steps.major-tag.outputs.major_tag_published }}
  major_tag:
    description: "Value of the published major tag, otherwise empty"
    value: ${{ steps.major-tag.outputs.major_tag }}
branding:
  icon: "package"
  color: "gray-dark"
runs:
  using: "composite"
  steps:
    - uses: rlespinasse/github-slug-action@v4
    - run: $GITHUB_ACTION_PATH/setup.sh
      shell: bash
      env:
        INPUT_DRYRUN: ${{ inputs.dry-run }}
        INPUT_WITHOUTPREFIX: ${{ inputs.without-prefix }}
    - name: Semantic Release
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v3
      with:
        dry_run: ${{ inputs.dry-run }}
        extra_plugins: |
          @semantic-release/commit-analyzer
          @semantic-release/release-notes-generator
          @semantic-release/git
          @semantic-release/github
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Major Tag Publication
      id: major-tag
      run: $GITHUB_ACTION_PATH/major-tag.sh
      shell: bash
      env:
        INPUT_DRYRUN: ${{ inputs.dry-run }}
        INPUT_MAJORTAG: ${{ inputs.major-tag }}
        INPUT_WITHOUTPREFIX: ${{ inputs.without-prefix }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        NEW_RELEASE_PUBLISHED: ${{ steps.semantic-release.outputs.new_release_published }}
        NEW_RELEASE_VERSION: ${{ steps.semantic-release.outputs.new_release_version }}
        NEW_RELEASE_MAJOR_VERSION: ${{ steps.semantic-release.outputs.new_release_major_version }}
