name: "Lerna system"
description: "Lerna system"
inputs:
  dry-run:
    description: "Whether to run lerna in `dry-run` mode"
    default: "false"
    required: true
  without-prefix:
    description: "Remove prefix from released version"
    default: "false"
    required: true
  github-token:
    description: "GitHub Token as provided by secrets"
    default: ${{ github.token }}
    required: true
runs:
  using: "composite"
  steps:
    - name: Launch lerna
      run: echo "Not Yet Supported"
      shell: bash
